openapi: 3.0.0
info:
  title: Jobs API
  contact: {}
  version: '1.0.0'
servers:
- url: https://jobapiapp.onrender.com/api/v1
  variables: {}

paths:
  /auth/register:
    post:
      tags:
      - Auth
      summary: Register
      operationId: Register
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/RegisterRequest'
              - example:
                  name: mithilesh kumar
                  email: mithilesh.kumar@gmail.com
                  password: 88888888abc
            example:
              name: mithilesh kumar
              email: mithilesh.kumar@gmail.com
              password: 88888888abc
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://jobapiapp.onrender.com/api/v1
        variables: {}
  /auth/login:
    post:
      tags:
      - Auth
      summary: Login
      operationId: Login
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/LoginRequest'
              - example:
                  email: mithilesh.kumar@gmail.com
                  password: 88888888abc
            example:
              email: mithilesh.kumar@gmail.com
              password: 88888888abc
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security: []
      servers:
      - url: https://jobapiapp.onrender.com/api/v1
        variables: {}
  /jobs:
    post:
      tags:
      - Jobs
      summary: Create Job
      operationId: CreateJob
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/CreateJobRequest'
              - example:
                  company: insta
                  position: react developer
            example:
              company: insta
              position: react developer
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://jobapiapp.onrender.com/api/v1
        variables: {}
    get:
      tags:
      - Jobs
      summary: Get All Jobs
      operationId: GetAllJobs
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://jobapiapp.onrender.com/api/v1
        variables: {}
  /jobs/{id}:
    parameters:
        - name: id
          in: path
          description: 'The user ID'
          required: true
          schema:
            type: string

    get:
      tags:
      - Jobs
      summary: Get Single Job
      operationId: GetSingleJob
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://jobapiapp.onrender.com/api/v1
        variables: {}
    patch:
      tags:
      - Jobs
      summary: Update Job
      operationId: UpdateJob
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/UpdateJobRequest'
              - example:
                  company: ''
            example:
              company: ''
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://jobapiapp.onrender.com/api/v1
        variables: {}
    delete:
      tags:
      - Jobs
      summary: Delete Jobs Copy
      operationId: DeleteJobsCopy
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
      security:
      - bearer: []
      servers:
      - url: https://jobapiapp.onrender.com/api/v1
        variables: {}
components:
  schemas:
    RegisterRequest:
      title: RegisterRequest
      required:
      - name
      - email
      - password
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
      example:
        name: mithilesh kumar
        email: mithilesh.kumar@gmail.com
        password: 88888888abc
    LoginRequest:
      title: LoginRequest
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: mithilesh.kumar@gmail.com
        password: 88888888abc
    CreateJobRequest:
      title: CreateJobRequest
      required:
      - company
      - position
      type: object
      properties:
        company:
          type: string
        position:
          type: string
      example:
        company: insta
        position: react developer
    UpdateJobRequest:
      title: UpdateJobRequest
      required:
      - company
      type: object
      properties:
        company:
          type: string
      example:
        company: ''
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
- name: Auth
  description: ''
- name: Jobs
  description: ''